language: python
python:
  - "2.7"
env:
  - TOX_ENV=coverageenv
install:
  - "pip install tox --download-cache $HOME/.pip-cache"
  - "pip install coveralls --download-cache $HOME/.pip-cache"
script:
  tox -e $TOX_ENV
after_success:
  coveralls
cache:
  directories:
    - .tox
    - $HOME/.pip-cache/
